try:
	trying_to_check_error
except NameError as err:
	print(err,'Error caused')
